name: Deploy

on: [push]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy
              uses: appleboy/ssh-action@master
              env:
                EC2_USER_PASSWORD: ${{ secrets.EC2_PASSWORD }}
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_PRIVATE_KEY }}
                port: ${{ secrets.EC2_PORT }}
                envs: EC2_USER_PASSWORD
                script: |
                  cd /home/deploy/fastapi-book-project
                  git pull origin main
                  python3 -m venv venv
                  source venv/bin/activate
                  pip3 install -r requirements.txt
                  sudo -S <<< $EC2_USER_PASSWORD systemctl start fastapi-book-project.service
                  sudo -S <<< $EC2_USER_PASSWORD systemctl status fastapi-book-project.service
