name: Test Fastapi Book Project

on:
    pull_request:
        branches: [main]

jobs: 
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python 3.12
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'

            - name: Install dependencies
              run: |
                python3 -m venv venv
                source venv/bin/activate
                pip3 install -r requirements.txt

            - name: Run tests
              run: |
                source venv/bin/activate
                pytest
