name: Test

on:
    pull_request:
        branches: [main]

jobs: 
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'

            - name: Install dependencies
              run: |
                python3 -m pip3 install --upgrade pip3
                pip3 install -r requirements.txt

            - name: Run tests
              run: |
                pytest
